DUNGEON : true # kick on death
DUNGEON_TIME: 24 # in hours
DUNGEON_MESSAGE: "&cYour king has fallen, you have been sent to the dungeon." # tempban message
teams:
  TEAM1:
    name: RED
    leader: null
    world: world
    x: 0.0
    y: 90.0
    z: 0.0
  TEAM2:
    name: BLUE
    leader: null
    world: world
    x: 0.0
    y: 90.0
    z: 0.0
  TEAM3:
    name: GREEN
    leader: null
    world: world
    x: 0.0
    y: 90.0
    z: 0.0
  TEAM4:
    name: YELLOW
    leader: null
    world: world
    x: 0.0
    y: 90.0
    z: 0.0
